app:
  image: "ababup1192/dodontof"
  ports:
    - "80:80"
  volumes:
    - "./saveData:/usr/local/apache2/saveData"
    - "./logs:/usr/local/apache2/htdocs/DodontoF/log.*:ro"
    - "./httpd.conf:/usr/local/apache2/conf/httpd.conf"
